//
//  AESoundConstants.swift
//  Touch League
//
//  Created by Marko Tadic on 5/15/16.
//  Copyright © 2016 AE. All rights reserved.
//

import AudioToolbox

// MARK: - AESystemSoundID

public struct AESystemSoundID {
    
    public static let MailReceived__new_mail: UInt32 = 1000
    public static let MailSent__mail_sent: UInt32 = 1001
    public static let VoicemailReceived__Voicemail: UInt32 = 1002
    public static let SMSReceived__ReceivedMessage: UInt32 = 1003
    public static let SMSSent__SentMessage: UInt32 = 1004
    public static let CalendarAlert__alarm: UInt32 = 1005
    public static let LowPower__low_power: UInt32 = 1006
    public static let SMSReceived_Alert__sms_received1: UInt32 = 1007
    public static let SMSReceived_Alert__sms_received2: UInt32 = 1008
    public static let SMSReceived_Alert__sms_received3: UInt32 = 1009
    public static let SMSReceived_Alert__sms_received4: UInt32 = 1010
    public static let SMSReceived_Vibrate___: UInt32 = 1011
    public static let SMSReceived_Alert__sms_received1_: UInt32 = 1012
    public static let SMSReceived_Alert__sms_received5: UInt32 = 1013
    public static let SMSReceived_Alert__sms_received6: UInt32 = 1014
    public static let Random__Voicemail: UInt32 = 1015
    public static let SMSSent__tweet_sent: UInt32 = 1016
    public static let SMSReceived_Alert__Anticipate: UInt32 = 1020
    public static let SMSReceived_Alert__Bloom: UInt32 = 1021
    public static let SMSReceived_Alert__Calypso: UInt32 = 1022
    public static let SMSReceived_Alert__Choo_Choo: UInt32 = 1023
    public static let SMSReceived_Alert__Descent: UInt32 = 1024
    public static let SMSReceived_Alert__Fanfare: UInt32 = 1025
    public static let SMSReceived_Alert__Ladder: UInt32 = 1026
    public static let SMSReceived_Alert__Minuet: UInt32 = 1027
    public static let SMSReceived_Alert__News_Flash: UInt32 = 1028
    public static let SMSReceived_Alert__Noir: UInt32 = 1029
    public static let SMSReceived_Alert__Sherwood_Forest: UInt32 = 1030
    public static let SMSReceived_Alert__Spell: UInt32 = 1031
    public static let SMSReceived_Alert__Suspense: UInt32 = 1032
    public static let SMSReceived_Alert__Telegraph: UInt32 = 1033
    public static let SMSReceived_Alert__Tiptoes: UInt32 = 1034
    public static let SMSReceived_Alert__Typewriters: UInt32 = 1035
    public static let SMSReceived_Alert__Update: UInt32 = 1036
    public static let USSDAlert__ussd: UInt32 = 1050
    public static let SIMToolkitTone__SIMToolkitCallDropped: UInt32 = 1051
    public static let SIMToolkitTone__SIMToolkitGeneralBeep: UInt32 = 1052
    public static let SIMToolkitTone__SIMToolkitNegativeACK: UInt32 = 1053
    public static let SIMToolkitTone__SIMToolkitPositiveACK: UInt32 = 1054
    public static let SIMToolkitTone__SIMToolkitSMS: UInt32 = 1055
    public static let PINKeyPressed__Tink: UInt32 = 1057
    public static let AudioToneBusy__ct_busy: UInt32 = 1070
    public static let AudioToneCongestion__ct_congestion: UInt32 = 1071
    public static let AudioTonePathAcknowledge__ct_path_ack: UInt32 = 1072
    public static let AudioToneError__ct_error: UInt32 = 1073
    public static let AudioToneCallWaiting__ct_call_waiting: UInt32 = 1074
    public static let AudioToneKey2__ct_keytone2: UInt32 = 1075
    public static let ScreenLocked__lock: UInt32 = 1100
    public static let ScreenUnlocked__unlock: UInt32 = 1101
    public static let FailedUnlock___: UInt32 = 1102
    public static let KeyPressed__Tink: UInt32 = 1103
    public static let KeyPressed__Tock: UInt32 = 1104
    public static let KeyPressed__Tock_: UInt32 = 1105
    public static let ConnectedToPower__beep_beep: UInt32 = 1106
    public static let RingerSwitchIndication__RingerChanged: UInt32 = 1107
    public static let CameraShutter__photoShutter: UInt32 = 1108
    public static let ShakeToShuffle__shake: UInt32 = 1109
    public static let JBL_Begin__jbl_begin: UInt32 = 1110
    public static let JBL_Confirm__jbl_confirm: UInt32 = 1111
    public static let JBL_Cancel__jbl_cancel: UInt32 = 1112
    public static let BeginRecording__begin_record: UInt32 = 1113
    public static let EndRecording__end_record: UInt32 = 1114
    public static let JBL_Ambiguous__jbl_ambiguous: UInt32 = 1115
    public static let JBL_NoMatch__jbl_no_match: UInt32 = 1116
    public static let BeginVideoRecording__begin_video_record: UInt32 = 1117
    public static let EndVideoRecording__end_video_record: UInt32 = 1118
    public static let VCInvitationAccepted__vc_invitation_accepted: UInt32 = 1150
    public static let VCRinging__vc_ringing: UInt32 = 1151
    public static let VCEnded__vc_ended: UInt32 = 1152
    public static let VCCallWaiting__ct_call_waiting: UInt32 = 1153
    public static let VCCallUpgrade__vc_ringing: UInt32 = 1154
    public static let TouchTone__dtmf_0: UInt32 = 1200
    public static let TouchTone__dtmf_1: UInt32 = 1201
    public static let TouchTone__dtmf_2: UInt32 = 1202
    public static let TouchTone__dtmf_3: UInt32 = 1203
    public static let TouchTone__dtmf_4: UInt32 = 1204
    public static let TouchTone__dtmf_5: UInt32 = 1205
    public static let TouchTone__dtmf_6: UInt32 = 1206
    public static let TouchTone__dtmf_7: UInt32 = 1207
    public static let TouchTone__dtmf_8: UInt32 = 1208
    public static let TouchTone__dtmf_9: UInt32 = 1209
    public static let TouchTone__dtmf_star: UInt32 = 1210
    public static let TouchTone__dtmf_pound: UInt32 = 1211
    public static let Headset_StartCall__long_low_short_high: UInt32 = 1254
    public static let Headset_Redial__short_double_high: UInt32 = 1255
    public static let Headset_AnswerCall__short_low_high: UInt32 = 1256
    public static let Headset_EndCall__short_double_low: UInt32 = 1257
    public static let Headset_CallWaitingActions__short_double_low: UInt32 = 1258
    public static let Headset_TransitionEnd__middle_9_short_double_low: UInt32 = 1259
    public static let SystemSoundPreview__Voicemail: UInt32 = 1300
    public static let SystemSoundPreview__ReceivedMessage: UInt32 = 1301
    public static let SystemSoundPreview__new_mail: UInt32 = 1302
    public static let SystemSoundPreview__mail_sent: UInt32 = 1303
    public static let SystemSoundPreview__alarm: UInt32 = 1304
    public static let SystemSoundPreview__lock: UInt32 = 1305
    public static let KeyPressClickPreview__Tock: UInt32 = 1306
    public static let SMSReceived_Selection__sms_received1: UInt32 = 1307
    public static let SMSReceived_Selection__sms_received2: UInt32 = 1308
    public static let SMSReceived_Selection__sms_received3: UInt32 = 1309
    public static let SMSReceived_Selection__sms_received4: UInt32 = 1310
    public static let SMSReceived_Vibrate____: UInt32 = 1311
    public static let SMSReceived_Selection__sms_received1_: UInt32 = 1312
    public static let SMSReceived_Selection__sms_received5: UInt32 = 1313
    public static let SMSReceived_Selection__sms_received6: UInt32 = 1314
    public static let SystemSoundPreview__Voicemail_: UInt32 = 1315
    public static let SMSReceived_Selection__Anticipate: UInt32 = 1320
    public static let SMSReceived_Selection__Bloom: UInt32 = 1321
    public static let SMSReceived_Selection__Calypso: UInt32 = 1322
    public static let SMSReceived_Selection__Choo_Choo: UInt32 = 1323
    public static let SMSReceived_Selection__Descent: UInt32 = 1324
    public static let SMSReceived_Selection__Fanfare: UInt32 = 1325
    public static let SMSReceived_Selection__Ladder: UInt32 = 1326
    public static let SMSReceived_Selection__Minuet: UInt32 = 1327
    public static let SMSReceived_Selection__News_Flash: UInt32 = 1328
    public static let SMSReceived_Selection__Noir: UInt32 = 1329
    public static let SMSReceived_Selection__Sherwood_Forest: UInt32 = 1330
    public static let SMSReceived_Selection__Spell: UInt32 = 1331
    public static let SMSReceived_Selection__Suspense: UInt32 = 1332
    public static let SMSReceived_Selection__Telegraph: UInt32 = 1333
    public static let SMSReceived_Selection__Tiptoes: UInt32 = 1334
    public static let SMSReceived_Selection__Typewriters: UInt32 = 1335
    public static let SMSReceived_Selection__Update: UInt32 = 1336
    public static let RingerVibeChanged___: UInt32 = 1350
    public static let SilentVibeChanged___: UInt32 = 1351
    public static let Vibrate___: UInt32 = 4095
    
}

// MARK: - AESystemSoundPath

public struct AESystemSoundPath {
    
    public static let AudioToneBusy__ct_busy = "/System/Library/Audio/UISounds/ct-busy.caf"
    public static let AudioToneCallWaiting__ct_call_waiting = "/System/Library/Audio/UISounds/ct-call-waiting.caf"
    public static let AudioToneCongestion__ct_congestion = "/System/Library/Audio/UISounds/ct-congestion.caf"
    public static let AudioToneError__ct_error = "/System/Library/Audio/UISounds/ct-error.caf"
    public static let AudioToneKey2__ct_keytone2 = "/System/Library/Audio/UISounds/ct-keytone2.caf"
    public static let AudioTonePathAcknowledge__ct_path_ack = "/System/Library/Audio/UISounds/ct-path-ack.caf"
    public static let BeginRecording__begin_record = "/System/Library/Audio/UISounds/begin_record.caf"
    public static let BeginVideoRecording__begin_video_record = "/System/Library/Audio/UISounds/begin_video_record.caf"
    public static let CalendarAlert__alarm = "/System/Library/Audio/UISounds/alarm.caf"
    public static let CameraShutter__photoShutter = "/System/Library/Audio/UISounds/photoShutter.caf"
    public static let ConnectedToPower__beep_beep = "/System/Library/Audio/UISounds/beep-beep.caf"
    public static let EndRecording__end_record = "/System/Library/Audio/UISounds/end_record.caf"
    public static let EndVideoRecording__end_video_record = "/System/Library/Audio/UISounds/end_video_record.caf"
    public static let Headset_AnswerCall__short_low_high = "/System/Library/Audio/UISounds/short_low_high.caf"
    public static let Headset_CallWaitingActions__short_double_low = "/System/Library/Audio/UISounds/middle_9_short_double_low.caf"
    public static let Headset_EndCall__short_double_low = "/System/Library/Audio/UISounds/middle_9_short_double_low.caf"
    public static let Headset_Redial__short_double_high = "/System/Library/Audio/UISounds/short_double_high.caf"
    public static let Headset_StartCall__long_low_short_high = "/System/Library/Audio/UISounds/long_low_short_high.caf"
    public static let Headset_TransitionEnd__middle_9_short_double_low = "/System/Library/Audio/UISounds/middle_9_short_double_low.caf"
    public static let JBL_Ambiguous__jbl_ambiguous = "/System/Library/Audio/UISounds/jbl_ambiguous.caf"
    public static let JBL_Begin__jbl_begin = "/System/Library/Audio/UISounds/jbl_begin.caf"
    public static let JBL_Cancel__jbl_cancel = "/System/Library/Audio/UISounds/jbl_cancel.caf"
    public static let JBL_Confirm__jbl_confirm = "/System/Library/Audio/UISounds/jbl_confirm.caf"
    public static let JBL_NoMatch__jbl_no_match = "/System/Library/Audio/UISounds/jbl_no_match.caf"
    public static let KeyPressClickPreview__Tock = "/System/Library/Audio/UISounds/Tock.caf"
    public static let KeyPressed__Tink = "/System/Library/Audio/UISounds/Tink.caf"
    public static let KeyPressed__Tock = "/System/Library/Audio/UISounds/Tock.caf"
    public static let LowPower__low_power = "/System/Library/Audio/UISounds/low_power.caf"
    public static let MailReceived__new_mail = "/System/Library/Audio/UISounds/new-mail.caf"
    public static let MailSent__mail_sent = "/System/Library/Audio/UISounds/mail-sent.caf"
    public static let Modern__airdrop_invite = "/System/Library/Audio/UISounds/Modern/airdrop_invite.caf"
    public static let Modern__calendar_alert_chord = "/System/Library/Audio/UISounds/Modern/calendar_alert_chord.caf"
    public static let Modern__camera_shutter_burst = "/System/Library/Audio/UISounds/Modern/camera_shutter_burst.caf"
    public static let Modern__camera_shutter_burst_begin = "/System/Library/Audio/UISounds/Modern/camera_shutter_burst_begin.caf"
    public static let Modern__camera_shutter_burst_end = "/System/Library/Audio/UISounds/Modern/camera_shutter_burst_end.caf"
    public static let Modern__sms_alert_aurora = "/System/Library/Audio/UISounds/Modern/sms_alert_aurora.caf"
    public static let Modern__sms_alert_bamboo = "/System/Library/Audio/UISounds/Modern/sms_alert_bamboo.caf"
    public static let Modern__sms_alert_circles = "/System/Library/Audio/UISounds/Modern/sms_alert_circles.caf"
    public static let Modern__sms_alert_complete = "/System/Library/Audio/UISounds/Modern/sms_alert_complete.caf"
    public static let Modern__sms_alert_hello = "/System/Library/Audio/UISounds/Modern/sms_alert_hello.caf"
    public static let Modern__sms_alert_input = "/System/Library/Audio/UISounds/Modern/sms_alert_input.caf"
    public static let Modern__sms_alert_keys = "/System/Library/Audio/UISounds/Modern/sms_alert_keys.caf"
    public static let Modern__sms_alert_note = "/System/Library/Audio/UISounds/Modern/sms_alert_note.caf"
    public static let Modern__sms_alert_popcorn = "/System/Library/Audio/UISounds/Modern/sms_alert_popcorn.caf"
    public static let Modern__sms_alert_synth = "/System/Library/Audio/UISounds/Modern/sms_alert_synth.caf"
    public static let Nano__3rdParty_DirectionDown_Haptic = "/System/Library/Audio/UISounds/nano/3rdParty_DirectionDown_Haptic.caf"
    public static let Nano__3rdParty_DirectionUp_Haptic = "/System/Library/Audio/UISounds/nano/3rdParty_DirectionUp_Haptic.caf"
    public static let Nano__3rdParty_Failure_Haptic = "/System/Library/Audio/UISounds/nano/3rdParty_Failure_Haptic.caf"
    public static let Nano__3rdParty_Retry_Haptic = "/System/Library/Audio/UISounds/nano/3rdParty_Retry_Haptic.caf"
    public static let Nano__3rdParty_Start_Haptic = "/System/Library/Audio/UISounds/nano/3rdParty_Start_Haptic.caf"
    public static let Nano__3rdParty_Stop_Haptic = "/System/Library/Audio/UISounds/nano/3rdParty_Stop_Haptic.caf"
    public static let Nano__3rdParty_Success_Haptic = "/System/Library/Audio/UISounds/nano/3rdParty_Success_Haptic.caf"
    public static let Nano__Alarm_Haptic = "/System/Library/Audio/UISounds/nano/Alarm_Haptic.caf"
    public static let Nano__Alarm_Nightstand_Haptic = "/System/Library/Audio/UISounds/nano/Alarm_Nightstand_Haptic.caf"
    public static let Nano__Alert_3rdParty_Haptic = "/System/Library/Audio/UISounds/nano/Alert_3rdParty_Haptic.caf"
    public static let Nano__Alert_3rdParty_Salient_Haptic = "/System/Library/Audio/UISounds/nano/Alert_3rdParty_Salient_Haptic.caf"
    public static let Nano__Alert_ActivityGoalAttained_Haptic = "/System/Library/Audio/UISounds/nano/Alert_ActivityGoalAttained_Haptic.caf"
    public static let Nano__Alert_ActivityGoalAttained_Salient_Haptic = "/System/Library/Audio/UISounds/nano/Alert_ActivityGoalAttained_Salient_Haptic.caf"
    public static let Nano__Alert_ActivityGoalBehind_Haptic = "/System/Library/Audio/UISounds/nano/Alert_ActivityGoalBehind_Haptic.caf"
    public static let Nano__Alert_ActivityGoalBehind_Salient_Haptic = "/System/Library/Audio/UISounds/nano/Alert_ActivityGoalBehind_Salient_Haptic.caf"
    public static let Nano__Alert_ActivityGoalClose_Haptic = "/System/Library/Audio/UISounds/nano/Alert_ActivityGoalClose_Haptic.caf"
    public static let Nano__Alert_BatteryLow_10p_Haptic = "/System/Library/Audio/UISounds/nano/Alert_BatteryLow_10p_Haptic.caf"
    public static let Nano__Alert_BatteryLow_5p_Haptic = "/System/Library/Audio/UISounds/nano/Alert_BatteryLow_5p_Haptic.caf"
    public static let Nano__Alert_BatteryLow_5p_Salient_Haptic = "/System/Library/Audio/UISounds/nano/Alert_BatteryLow_5p_Salient_Haptic.caf"
    public static let Nano__Alert_Calendar_Haptic = "/System/Library/Audio/UISounds/nano/Alert_Calendar_Haptic.caf"
    public static let Nano__Alert_Calendar_Salient_Haptic = "/System/Library/Audio/UISounds/nano/Alert_Calendar_Salient_Haptic.caf"
    public static let Nano__Alert_Mail_Haptic = "/System/Library/Audio/UISounds/nano/Alert_Mail_Haptic.caf"
    public static let Nano__Alert_Mail_Salient_Haptic = "/System/Library/Audio/UISounds/nano/Alert_Mail_Salient_Haptic.caf"
    public static let Nano__Alert_MapsDirectionsInApp_Haptic = "/System/Library/Audio/UISounds/nano/Alert_MapsDirectionsInApp_Haptic.caf"
    public static let Nano__Alert_Messages_1_Haptic = "/System/Library/Audio/UISounds/nano/Alert_Messages_1_Haptic.caf"
    public static let Nano__Alert_Messages_1_Salient_Haptic = "/System/Library/Audio/UISounds/nano/Alert_Messages_1_Salient_Haptic.caf"
    public static let Nano__Alert_Messages_2_Haptic = "/System/Library/Audio/UISounds/nano/Alert_Messages_2_Haptic.caf"
    public static let Nano__Alert_Messages_3_Haptic = "/System/Library/Audio/UISounds/nano/Alert_Messages_3_Haptic.caf"
    public static let Nano__Alert_PassbookBalance_Haptic = "/System/Library/Audio/UISounds/nano/Alert_PassbookBalance_Haptic.caf"
    public static let Nano__Alert_PassbookGeofence_Haptic = "/System/Library/Audio/UISounds/nano/Alert_PassbookGeofence_Haptic.caf"
    public static let Nano__Alert_PassbookGeofence_Salient_Haptic = "/System/Library/Audio/UISounds/nano/Alert_PassbookGeofence_Salient_Haptic.caf"
    public static let Nano__Alert_PhotostreamActivity_Haptic = "/System/Library/Audio/UISounds/nano/Alert_PhotostreamActivity_Haptic.caf"
    public static let Nano__Alert_ReminderDue_Haptic = "/System/Library/Audio/UISounds/nano/Alert_ReminderDue_Haptic.caf"
    public static let Nano__Alert_ReminderDue_Salient_Haptic = "/System/Library/Audio/UISounds/nano/Alert_ReminderDue_Salient_Haptic.caf"
    public static let Nano__Alert_Voicemail_Haptic = "/System/Library/Audio/UISounds/nano/Alert_Voicemail_Haptic.caf"
    public static let Nano__Alert_Voicemail_Salient_Haptic = "/System/Library/Audio/UISounds/nano/Alert_Voicemail_Salient_Haptic.caf"
    public static let Nano__Alert_WalkieTalkie_Haptic = "/System/Library/Audio/UISounds/nano/Alert_WalkieTalkie_Haptic.caf"
    public static let Nano__BatteryMagsafe_Haptic = "/System/Library/Audio/UISounds/nano/BatteryMagsafe_Haptic.caf"
    public static let Nano__Beat_Haptic = "/System/Library/Audio/UISounds/nano/Beat_Haptic.caf"
    public static let Nano__BuddyPairingFailure_Haptic = "/System/Library/Audio/UISounds/nano/BuddyPairingFailure_Haptic.caf"
    public static let Nano__BuddyPairingRemoteConnection_Haptic = "/System/Library/Audio/UISounds/nano/BuddyPairingRemoteConnection_Haptic.caf"
    public static let Nano__BuddyPairingRemoteTap_Haptic = "/System/Library/Audio/UISounds/nano/BuddyPairingRemoteTap_Haptic.caf"
    public static let Nano__BuddyPairingSuccess_Haptic = "/System/Library/Audio/UISounds/nano/BuddyPairingSuccess_Haptic.caf"
    public static let Nano__busy_tone_ansi = "/System/Library/Audio/UISounds/nano/busy_tone_ansi.caf"
    public static let Nano__busy_tone_cept = "/System/Library/Audio/UISounds/nano/busy_tone_cept.caf"
    public static let Nano__call_waiting_tone_ansi = "/System/Library/Audio/UISounds/nano/call_waiting_tone_ansi.caf"
    public static let Nano__call_waiting_tone_cept = "/System/Library/Audio/UISounds/nano/call_waiting_tone_cept.caf"
    public static let Nano__CameraCountdownImminent_Haptic = "/System/Library/Audio/UISounds/nano/CameraCountdownImminent_Haptic.caf"
    public static let Nano__CameraCountdownTick_Haptic = "/System/Library/Audio/UISounds/nano/CameraCountdownTick_Haptic.caf"
    public static let Nano__CameraShutter_Haptic = "/System/Library/Audio/UISounds/nano/CameraShutter_Haptic.caf"
    public static let Nano__ct_call_waiting = "/System/Library/Audio/UISounds/nano/ct-call-waiting.caf"
    public static let Nano__Detent_Haptic = "/System/Library/Audio/UISounds/nano/Detent_Haptic.caf"
    public static let Nano__DoNotDisturb_Haptic = "/System/Library/Audio/UISounds/nano/DoNotDisturb_Haptic.caf"
    public static let Nano__end_call_tone_cept = "/System/Library/Audio/UISounds/nano/end_call_tone_cept.caf"
    public static let Nano__ET_BeginNotification_Haptic = "/System/Library/Audio/UISounds/nano/ET_BeginNotification_Haptic.caf"
    public static let Nano__ET_BeginNotification_Salient_Haptic = "/System/Library/Audio/UISounds/nano/ET_BeginNotification_Salient_Haptic.caf"
    public static let Nano__ET_RemoteTap_Receive_Haptic = "/System/Library/Audio/UISounds/nano/ET_RemoteTap_Receive_Haptic.caf"
    public static let Nano__ET_RemoteTap_Send_Haptic = "/System/Library/Audio/UISounds/nano/ET_RemoteTap_Send_Haptic.caf"
    public static let Nano__Experimental_Orb1_Haptic = "/System/Library/Audio/UISounds/nano/Experimental_Orb1_Haptic.caf"
    public static let Nano__Experimental_Orb2_Haptic = "/System/Library/Audio/UISounds/nano/Experimental_Orb2_Haptic.caf"
    public static let Nano__Experimental_Orb3_Haptic = "/System/Library/Audio/UISounds/nano/Experimental_Orb3_Haptic.caf"
    public static let Nano__Experimental_Orb4_Haptic = "/System/Library/Audio/UISounds/nano/Experimental_Orb4_Haptic.caf"
    public static let Nano__Experimental_Orb5_Haptic = "/System/Library/Audio/UISounds/nano/Experimental_Orb5_Haptic.caf"
    public static let Nano__HourlyChime_Haptic = "/System/Library/Audio/UISounds/nano/HourlyChime_Haptic.caf"
    public static let Nano__MessagesIncoming_Haptic = "/System/Library/Audio/UISounds/nano/MessagesIncoming_Haptic.caf"
    public static let Nano__MessagesOutgoing_Haptic = "/System/Library/Audio/UISounds/nano/MessagesOutgoing_Haptic.caf"
    public static let Nano__NavigationGenericManeuver_Haptic = "/System/Library/Audio/UISounds/nano/NavigationGenericManeuver_Haptic.caf"
    public static let Nano__NavigationGenericManeuver_Salient_Haptic = "/System/Library/Audio/UISounds/nano/NavigationGenericManeuver_Salient_Haptic.caf"
    public static let Nano__NavigationLeftTurn_Haptic = "/System/Library/Audio/UISounds/nano/NavigationLeftTurn_Haptic.caf"
    public static let Nano__NavigationLeftTurn_Salient_Haptic = "/System/Library/Audio/UISounds/nano/NavigationLeftTurn_Salient_Haptic.caf"
    public static let Nano__NavigationRightTurn_Haptic = "/System/Library/Audio/UISounds/nano/NavigationRightTurn_Haptic.caf"
    public static let Nano__NavigationRightTurn_Salient_Haptic = "/System/Library/Audio/UISounds/nano/NavigationRightTurn_Salient_Haptic.caf"
    public static let Nano__Notification_Haptic = "/System/Library/Audio/UISounds/nano/Notification_Haptic.caf"
    public static let Nano__Notification_Salient_Haptic = "/System/Library/Audio/UISounds/nano/Notification_Salient_Haptic.caf"
    public static let Nano__OnOffPasscodeFailure_Haptic = "/System/Library/Audio/UISounds/nano/OnOffPasscodeFailure_Haptic.caf"
    public static let Nano__OnOffPasscodeUnlock_Haptic = "/System/Library/Audio/UISounds/nano/OnOffPasscodeUnlock_Haptic.caf"
    public static let Nano__OnOffPasscodeUnlockCampanion_Haptic = "/System/Library/Audio/UISounds/nano/OnOffPasscodeUnlockCampanion_Haptic.caf"
    public static let Nano__OrbExit_Haptic = "/System/Library/Audio/UISounds/nano/OrbExit_Haptic.caf"
    public static let Nano__OrbLayers_Haptic = "/System/Library/Audio/UISounds/nano/OrbLayers_Haptic.caf"
    public static let Nano__PhoneAnswer_Haptic = "/System/Library/Audio/UISounds/nano/PhoneAnswer_Haptic.caf"
    public static let Nano__PhoneHangUp_Haptic = "/System/Library/Audio/UISounds/nano/PhoneHangUp_Haptic.caf"
    public static let Nano__PhoneHold_Haptic = "/System/Library/Audio/UISounds/nano/PhoneHold_Haptic.caf"
    public static let Nano__PhotosZoomDetent_Haptic = "/System/Library/Audio/UISounds/nano/PhotosZoomDetent_Haptic.caf"
    public static let Nano__Preview_AudioAndHaptic = "/System/Library/Audio/UISounds/nano/Preview_AudioAndHaptic.caf"
    public static let Nano__QB_Dictation_Haptic = "/System/Library/Audio/UISounds/nano/QB_Dictation_Haptic.caf"
    public static let Nano__QB_Dictation_Off_Haptic = "/System/Library/Audio/UISounds/nano/QB_Dictation_Off_Haptic.caf"
    public static let Nano__ringback_tone_ansi = "/System/Library/Audio/UISounds/nano/ringback_tone_ansi.caf"
    public static let Nano__ringback_tone_aus = "/System/Library/Audio/UISounds/nano/ringback_tone_aus.caf"
    public static let Nano__ringback_tone_cept = "/System/Library/Audio/UISounds/nano/ringback_tone_cept.caf"
    public static let Nano__ringback_tone_hk = "/System/Library/Audio/UISounds/nano/ringback_tone_hk.caf"
    public static let Nano__Ringtone_UK_Haptic = "/System/Library/Audio/UISounds/nano/Ringtone_UK_Haptic.caf"
    public static let Nano__Ringtone_US_Haptic = "/System/Library/Audio/UISounds/nano/Ringtone_US_Haptic.caf"
    public static let Nano__RingtoneDucked_UK_Haptic = "/System/Library/Audio/UISounds/nano/RingtoneDucked_UK_Haptic.caf"
    public static let Nano__RingtoneDucked_US_Haptic = "/System/Library/Audio/UISounds/nano/RingtoneDucked_US_Haptic.caf"
    public static let Nano__SalientNotification_Haptic = "/System/Library/Audio/UISounds/nano/SalientNotification_Haptic.caf"
    public static let Nano__SedentaryTimer_Haptic = "/System/Library/Audio/UISounds/nano/SedentaryTimer_Haptic.caf"
    public static let Nano__SedentaryTimer_Salient_Haptic = "/System/Library/Audio/UISounds/nano/SedentaryTimer_Salient_Haptic.caf"
    public static let Nano__SiriStart_Haptic = "/System/Library/Audio/UISounds/nano/SiriStart_Haptic.caf"
    public static let Nano__SiriStopFailure_Haptic = "/System/Library/Audio/UISounds/nano/SiriStopFailure_Haptic.caf"
    public static let Nano__SiriStopSuccess_Haptic = "/System/Library/Audio/UISounds/nano/SiriStopSuccess_Haptic.caf"
    public static let Nano__Stockholm_Haptic = "/System/Library/Audio/UISounds/nano/Stockholm_Haptic.caf"
    public static let Nano__StockholmActive_Haptic = "/System/Library/Audio/UISounds/nano/StockholmActive_Haptic.caf"
    public static let Nano__StockholmActiveSingleCycle_Haptic = "/System/Library/Audio/UISounds/nano/StockholmActiveSingleCycle_Haptic.caf"
    public static let Nano__StockholmFailure_Haptic = "/System/Library/Audio/UISounds/nano/StockholmFailure_Haptic.caf"
    public static let Nano__StopwatchLap_Haptic = "/System/Library/Audio/UISounds/nano/StopwatchLap_Haptic.caf"
    public static let Nano__StopwatchReset_Haptic = "/System/Library/Audio/UISounds/nano/StopwatchReset_Haptic.caf"
    public static let Nano__StopwatchStart_Haptic = "/System/Library/Audio/UISounds/nano/StopwatchStart_Haptic.caf"
    public static let Nano__StopwatchStop_Haptic = "/System/Library/Audio/UISounds/nano/StopwatchStop_Haptic.caf"
    public static let Nano__SwTest1_Haptic = "/System/Library/Audio/UISounds/nano/SwTest1_Haptic.caf"
    public static let Nano__SystemStartup_Haptic = "/System/Library/Audio/UISounds/nano/SystemStartup_Haptic.caf"
    public static let Nano__Timer_Haptic = "/System/Library/Audio/UISounds/nano/Timer_Haptic.caf"
    public static let Nano__TimerCancel_Haptic = "/System/Library/Audio/UISounds/nano/TimerCancel_Haptic.caf"
    public static let Nano__TimerPause_Haptic = "/System/Library/Audio/UISounds/nano/TimerPause_Haptic.caf"
    public static let Nano__TimerStart_Haptic = "/System/Library/Audio/UISounds/nano/TimerStart_Haptic.caf"
    public static let Nano__TimerWheelHoursDetent_Haptic = "/System/Library/Audio/UISounds/nano/TimerWheelHoursDetent_Haptic.caf"
    public static let Nano__TimerWheelMinutesDetent_Haptic = "/System/Library/Audio/UISounds/nano/TimerWheelMinutesDetent_Haptic.caf"
    public static let Nano__UISwipe_Haptic = "/System/Library/Audio/UISounds/nano/UISwipe_Haptic.caf"
    public static let Nano__UISwitch_Off_Haptic = "/System/Library/Audio/UISounds/nano/UISwitch_Off_Haptic.caf"
    public static let Nano__UISwitch_On_Haptic = "/System/Library/Audio/UISounds/nano/UISwitch_On_Haptic.caf"
    public static let Nano__vc_ended = "/System/Library/Audio/UISounds/nano/vc~ended.caf"
    public static let Nano__vc_invitation_accepted = "/System/Library/Audio/UISounds/nano/vc~invitation-accepted.caf"
    public static let Nano__vc_ringing = "/System/Library/Audio/UISounds/nano/vc~ringing.caf"
    public static let Nano__VoiceOver_Click_Haptic = "/System/Library/Audio/UISounds/nano/VoiceOver_Click_Haptic.caf"
    public static let Nano__WalkieTalkieActiveEnd_Haptic = "/System/Library/Audio/UISounds/nano/WalkieTalkieActiveEnd_Haptic.caf"
    public static let Nano__WalkieTalkieActiveStart_Haptic = "/System/Library/Audio/UISounds/nano/WalkieTalkieActiveStart_Haptic.caf"
    public static let Nano__WorkoutComplete_Haptic = "/System/Library/Audio/UISounds/nano/WorkoutComplete_Haptic.caf"
    public static let Nano__WorkoutCountdown_Haptic = "/System/Library/Audio/UISounds/nano/WorkoutCountdown_Haptic.caf"
    public static let Nano__WorkoutPressStart_Haptic = "/System/Library/Audio/UISounds/nano/WorkoutPressStart_Haptic.caf"
    public static let Nano__WorkoutSaved_Haptic = "/System/Library/Audio/UISounds/nano/WorkoutSaved_Haptic.caf"
    public static let Nano__WorkoutSelect_Haptic = "/System/Library/Audio/UISounds/nano/WorkoutSelect_Haptic.caf"
    public static let PINKeyPressed__Tink = "/System/Library/Audio/UISounds/Tink.caf"
    public static let Random__connect_power = "/System/Library/Audio/UISounds/connect_power.caf"
    public static let Random__focus_change_app_icon = "/System/Library/Audio/UISounds/focus_change_app_icon.caf"
    public static let Random__focus_change_keyboard = "/System/Library/Audio/UISounds/focus_change_keyboard.caf"
    public static let Random__focus_change_large = "/System/Library/Audio/UISounds/focus_change_large.caf"
    public static let Random__focus_change_small = "/System/Library/Audio/UISounds/focus_change_small.caf"
    public static let Random__keyboard_press_clear = "/System/Library/Audio/UISounds/keyboard_press_clear.caf"
    public static let Random__keyboard_press_delete = "/System/Library/Audio/UISounds/keyboard_press_delete.caf"
    public static let Random__keyboard_press_normal = "/System/Library/Audio/UISounds/keyboard_press_normal.caf"
    public static let Random__navigation_pop = "/System/Library/Audio/UISounds/navigation_pop.caf"
    public static let Random__navigation_push = "/System/Library/Audio/UISounds/navigation_push.caf"
    public static let Random__payment_failure = "/System/Library/Audio/UISounds/payment_failure.caf"
    public static let Random__payment_success = "/System/Library/Audio/UISounds/payment_success.caf"
    public static let Random__short_double_low = "/System/Library/Audio/UISounds/short_double_low.caf"
    public static let Random__Swish = "/System/Library/Audio/UISounds/Swish.caf"
    public static let Random__Voicemail = "/System/Library/Audio/UISounds/Voicemail.caf"
    public static let RingerSwitchIndication__RingerChanged = "/System/Library/Audio/UISounds/RingerChanged.caf"
    public static let ScreenLocked__lock = "/System/Library/Audio/UISounds/lock.caf"
    public static let ScreenUnlocked__unlock = "/System/Library/Audio/UISounds/unlock.caf"
    public static let ShakeToShuffle__shake = "/System/Library/Audio/UISounds/shake.caf"
    public static let SIMToolkitTone__SIMToolkitCallDropped = "/System/Library/Audio/UISounds/SIMToolkitCallDropped.caf"
    public static let SIMToolkitTone__SIMToolkitGeneralBeep = "/System/Library/Audio/UISounds/SIMToolkitGeneralBeep.caf"
    public static let SIMToolkitTone__SIMToolkitNegativeACK = "/System/Library/Audio/UISounds/SIMToolkitNegativeACK.caf"
    public static let SIMToolkitTone__SIMToolkitPositiveACK = "/System/Library/Audio/UISounds/SIMToolkitPositiveACK.caf"
    public static let SIMToolkitTone__SIMToolkitSMS = "/System/Library/Audio/UISounds/SIMToolkitSMS.caf"
    public static let SMSReceived__ReceivedMessage = "/System/Library/Audio/UISounds/ReceivedMessage.caf"
    public static let SMSReceived_Alert__Anticipate = "/System/Library/Audio/UISounds/New/Anticipate.caf"
    public static let SMSReceived_Alert__Bloom = "/System/Library/Audio/UISounds/New/Bloom.caf"
    public static let SMSReceived_Alert__Calypso = "/System/Library/Audio/UISounds/New/Calypso.caf"
    public static let SMSReceived_Alert__Choo_Choo = "/System/Library/Audio/UISounds/New/Choo_Choo.caf"
    public static let SMSReceived_Alert__Descent = "/System/Library/Audio/UISounds/New/Descent.caf"
    public static let SMSReceived_Alert__Fanfare = "/System/Library/Audio/UISounds/New/Fanfare.caf"
    public static let SMSReceived_Alert__Ladder = "/System/Library/Audio/UISounds/New/Ladder.caf"
    public static let SMSReceived_Alert__Minuet = "/System/Library/Audio/UISounds/New/Minuet.caf"
    public static let SMSReceived_Alert__News_Flash = "/System/Library/Audio/UISounds/New/News_Flash.caf"
    public static let SMSReceived_Alert__Noir = "/System/Library/Audio/UISounds/New/Noir.caf"
    public static let SMSReceived_Alert__Sherwood_Forest = "/System/Library/Audio/UISounds/New/Sherwood_Forest.caf"
    public static let SMSReceived_Alert__sms_received1 = "/System/Library/Audio/UISounds/sms-received1.caf"
    public static let SMSReceived_Alert__sms_received2 = "/System/Library/Audio/UISounds/sms-received2.caf"
    public static let SMSReceived_Alert__sms_received3 = "/System/Library/Audio/UISounds/sms-received3.caf"
    public static let SMSReceived_Alert__sms_received4 = "/System/Library/Audio/UISounds/sms-received4.caf"
    public static let SMSReceived_Alert__sms_received5 = "/System/Library/Audio/UISounds/sms-received5.caf"
    public static let SMSReceived_Alert__sms_received6 = "/System/Library/Audio/UISounds/sms-received6.caf"
    public static let SMSReceived_Alert__Spell = "/System/Library/Audio/UISounds/New/Spell.caf"
    public static let SMSReceived_Alert__Suspense = "/System/Library/Audio/UISounds/New/Suspense.caf"
    public static let SMSReceived_Alert__Telegraph = "/System/Library/Audio/UISounds/New/Telegraph.caf"
    public static let SMSReceived_Alert__Tiptoes = "/System/Library/Audio/UISounds/New/Tiptoes.caf"
    public static let SMSReceived_Alert__Typewriters = "/System/Library/Audio/UISounds/New/Typewriters.caf"
    public static let SMSReceived_Alert__Update = "/System/Library/Audio/UISounds/New/Update.caf"
    public static let SMSReceived_Selection__Anticipate = "/System/Library/Audio/UISounds/New/Anticipate.caf"
    public static let SMSReceived_Selection__Bloom = "/System/Library/Audio/UISounds/New/Bloom.caf"
    public static let SMSReceived_Selection__Calypso = "/System/Library/Audio/UISounds/New/Calypso.caf"
    public static let SMSReceived_Selection__Choo_Choo = "/System/Library/Audio/UISounds/New/Choo_Choo.caf"
    public static let SMSReceived_Selection__Descent = "/System/Library/Audio/UISounds/New/Descent.caf"
    public static let SMSReceived_Selection__Fanfare = "/System/Library/Audio/UISounds/New/Fanfare.caf"
    public static let SMSReceived_Selection__Ladder = "/System/Library/Audio/UISounds/New/Ladder.caf"
    public static let SMSReceived_Selection__Minuet = "/System/Library/Audio/UISounds/New/Minuet.caf"
    public static let SMSReceived_Selection__News_Flash = "/System/Library/Audio/UISounds/New/News_Flash.caf"
    public static let SMSReceived_Selection__Noir = "/System/Library/Audio/UISounds/New/Noir.caf"
    public static let SMSReceived_Selection__Sherwood_Forest = "/System/Library/Audio/UISounds/New/Sherwood_Forest.caf"
    public static let SMSReceived_Selection__sms_received1 = "/System/Library/Audio/UISounds/sms-received1.caf"
    public static let SMSReceived_Selection__sms_received2 = "/System/Library/Audio/UISounds/sms-received2.caf"
    public static let SMSReceived_Selection__sms_received3 = "/System/Library/Audio/UISounds/sms-received3.caf"
    public static let SMSReceived_Selection__sms_received4 = "/System/Library/Audio/UISounds/sms-received4.caf"
    public static let SMSReceived_Selection__sms_received5 = "/System/Library/Audio/UISounds/sms-received5.caf"
    public static let SMSReceived_Selection__sms_received6 = "/System/Library/Audio/UISounds/sms-received6.caf"
    public static let SMSReceived_Selection__Spell = "/System/Library/Audio/UISounds/New/Spell.caf"
    public static let SMSReceived_Selection__Suspense = "/System/Library/Audio/UISounds/New/Suspense.caf"
    public static let SMSReceived_Selection__Telegraph = "/System/Library/Audio/UISounds/New/Telegraph.caf"
    public static let SMSReceived_Selection__Tiptoes = "/System/Library/Audio/UISounds/New/Tiptoes.caf"
    public static let SMSReceived_Selection__Typewriters = "/System/Library/Audio/UISounds/New/Typewriters.caf"
    public static let SMSReceived_Selection__Update = "/System/Library/Audio/UISounds/New/Update.caf"
    public static let SMSSent__SentMessage = "/System/Library/Audio/UISounds/SentMessage.caf"
    public static let SMSSent__tweet_sent = "/System/Library/Audio/UISounds/tweet_sent.caf"
    public static let SystemSoundPreview__alarm = "/System/Library/Audio/UISounds/alarm.caf"
    public static let SystemSoundPreview__lock = "/System/Library/Audio/UISounds/lock.caf"
    public static let SystemSoundPreview__mail_sent = "/System/Library/Audio/UISounds/mail-sent.caf"
    public static let SystemSoundPreview__new_mail = "/System/Library/Audio/UISounds/new-mail.caf"
    public static let SystemSoundPreview__ReceivedMessage = "/System/Library/Audio/UISounds/ReceivedMessage.caf"
    public static let SystemSoundPreview__Voicemail = "/System/Library/Audio/UISounds/Voicemail.caf"
    public static let TouchTone__dtmf_0 = "/System/Library/Audio/UISounds/dtmf-0.caf"
    public static let TouchTone__dtmf_1 = "/System/Library/Audio/UISounds/dtmf-1.caf"
    public static let TouchTone__dtmf_2 = "/System/Library/Audio/UISounds/dtmf-2.caf"
    public static let TouchTone__dtmf_3 = "/System/Library/Audio/UISounds/dtmf-3.caf"
    public static let TouchTone__dtmf_4 = "/System/Library/Audio/UISounds/dtmf-4.caf"
    public static let TouchTone__dtmf_5 = "/System/Library/Audio/UISounds/dtmf-5.caf"
    public static let TouchTone__dtmf_6 = "/System/Library/Audio/UISounds/dtmf-6.caf"
    public static let TouchTone__dtmf_7 = "/System/Library/Audio/UISounds/dtmf-7.caf"
    public static let TouchTone__dtmf_8 = "/System/Library/Audio/UISounds/dtmf-8.caf"
    public static let TouchTone__dtmf_9 = "/System/Library/Audio/UISounds/dtmf-9.caf"
    public static let TouchTone__dtmf_pound = "/System/Library/Audio/UISounds/dtmf-pound.caf"
    public static let TouchTone__dtmf_star = "/System/Library/Audio/UISounds/dtmf-star.caf"
    public static let USSDAlert__ussd = "/System/Library/Audio/UISounds/ussd.caf"
    public static let VCCallUpgrade__vc_ringing = "/System/Library/Audio/UISounds/vc~ringing.caf"
    public static let VCCallWaiting__ct_call_waiting = "/System/Library/Audio/UISounds/ct-call-waiting.caf"
    public static let VCEnded__vc_ended = "/System/Library/Audio/UISounds/vc~ended.caf"
    public static let VCInvitationAccepted__vc_invitation_accepted = "/System/Library/Audio/UISounds/vc~invitation-accepted.caf"
    public static let VCRinging__vc_ringing = "/System/Library/Audio/UISounds/vc~ringing.caf"
    public static let VoicemailReceived__Voicemail = "/System/Library/Audio/UISounds/Voicemail.caf"
    
}
